package com.orderly.api.admin.domain.model;

public enum AdminAction {
    BUSINESS_SUSPENDED,
    BUSINESS_ACTIVATED,
    BUSINESS_DELETED,
    PLAN_CHANGED,
    TRIAL_EXTENDED,
    FREE_MONTHS_GRANTED,
    USAGE_RESET,
    BUSINESS_IMPERSONATED,
    FORCE_LOGOUT,
    EMAIL_SENT,
    BUSINESS_CREATED,
    CANCELLED_BUSINESSES_PURGED
}
